---
title: "Statistik II - Vorbereitungsaufgabe"
subtitle: "04 - Statistisches Hypothesentesten I"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Beschreibung der Erklärung

Für diese Vorbereitungsaufgabe schreibst du eine Erklärung zum Thema *Statistisches Hypothesentesten*. Unter einer Erklärung versteht man einen Text, der in Lehr-Lern-Kontexten eingesetzt wird, um das Wissen oder das Verständnis des Lerngegenstands der Lernenden zu erweitern. Deine Erklärung sollte in etwa 800 Wörter umfassen und für eine\*n Erstsemester\*in welche\*r kein Vorwissen über Statistisches Hypothesentesten hat, geschrieben sein. Auf folgende Begriffe solltest du in deiner Erklärung eingehen:

* Nullhypothese
* Alternativhypothese
* Statistische Hypothese
* z-Test
* Signifikanzniveau

Schreibe einen Fließtext (keine Aufzählungen). Achte bei der Anfertigung der Erklärung darauf, dass deine Zielgruppe in der Lage ist, den Text ohne Zuhilfenahme anderer Materialien zu verstehen.

# Erklärung zum Thema Statistisches Hypothesentesten

TODO: Füge hier deine ~ 800 Wörter lange Erklärung ein. 